travis:
  secure:
    BINSTAR_TOKEN: az6p6g3fFrJguI9sWhHljPyNe9bjuNp8gExF77CxYh7TBBFHnKZZTx3HCCw1/53uHpLCDyvDVoUwSn26LolKuqfAxka1rvcCYCEze4Nd3U5wMV7KT80ERAtETlu5g1xsuwur/Xh9eNM9YdJ1e8m7n2xbESfLpUp9unWx6emFVoPdZVD4pORSp9GnR4QRgWX/1rg8lAJ303ISlfIcmpuj1xGBlXFGoI5XbTcEyUssAERRVtjl2mI9dFIdsaNEZMquy3cTbSrzdvCh0wC/bPfh8xcHlh/PqnOvPjqQ/Vc1Z3r9ZxfCj06F8blYfe4hn2EraVA+dxFG2iiiLyCt12xrh7KvSHkWZDFAymXoxknD6uKhuwiZqars9nX9vTFsCmbv49Ou+bkCp12YwIzwwZdDz1dMUhZUXhr0+fAzFc+dyRw6ZpIDUdVlWUKwCLY8CSS7PHqBKGpXjXMoYpWq1FK+zwDuhaxo7gTRztYcPX5TXjVzpTdyus2LE6v3zTaUWylKKhX0tcMWYQ+o7HFxsqpWmw4UKlRqxP5E+KTHp1MYvGlt4rpURQeIFzumUZ/vodZRot8JiNha/l2whyb1xgcgX16ui3gh2NCSQH3c+en3QZhCdqkp/ZiuE4j5jnlqaDqRsN1pSNRKqP/YGdsV40W7Uqf6/Yok8JcpCNLzs+88/v0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
